name: Trigger Workflow in Repo B

on:
  release:
    types: [published]

jobs:
  trigger-repo-b-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Repository B
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TRIGGER_SECRET: $${{ secrets.TRIGGER_SECRET }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "X-Trigger-Secret: $TRIGGER_SECRET" \
            https://api.github.com/repos/soham30rane/github-actions-demo/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main","inputs":{"release_tag":"'"$RELEASE_TAG"'"}}'